name: Publish to npm and JSR

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to npm and JSR
    runs-on: ubuntu-latest
    needs: build
    if: success()

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public

      - name: Publish to JSR
        run: npx jsr publish
